# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2024-2026 FreeSDN
"""One-shot cleanup: soft-delete test-fixture organizations.

Background: test runs in this repo create disposable orgs with
predictable name prefixes (``fleet-*``, ``offline-*``, ``test-org-*``
etc). Over time these accumulate because the test cleanup paths
can be FK-blocked by leftover schedule_runs / discovered_hosts /
notification rows. The agent fleet dashboard's "93 agents" count
that should be "1 real agent" is the user-visible symptom.

This script:
1. Identifies orgs whose name matches a fixture prefix AND have no
   real-content signal (0 devices, 0 controllers).
2. Soft-deletes them (sets ``deleted_at = now()``). The dependent
   sites / agents / discovered_hosts cascade via the
   ``WHERE deleted_at IS NULL`` filters in the query layer; this
   script also stamps deleted_at on those tables for cleanliness.
3. Idempotent — running twice is a no-op.

Safety:
- Soft-delete only. Hard-purge requires a follow-up.
- Refuses to touch any org that owns >0 ``devices.devices`` rows
  (real adopted inventory means it's NOT a fixture).
- Lists what it will do and asks for confirmation when run
  interactively. When ``--yes`` is passed (CI / scripted use),
  proceeds without prompting.

Usage::

    docker exec freesdn-api python -m app.scripts.purge_fixture_orgs --yes
"""

from __future__ import annotations

import argparse
import asyncio
import logging
import sys
from datetime import UTC, datetime

from sqlalchemy import text

logger = logging.getLogger(__name__)

# Fixture org name prefixes generated by the test suite. Anything
# matching one of these AND with no device inventory is a candidate
# for cleanup.
FIXTURE_PREFIXES = (
    "fleet-",
    "offline-",
    "test-org-",
    "pipeline-org-",
    "runs-org-",
    "other-",
    "topo-org-",
    "iscan-",
    "audit-",  # audit-pattern test scaffolding
    "ws-test-",  # ws_client_integration test orgs
    "aa-",  # auto-adopt test fixtures (site_with_auto_adopt)
    "noaa-",  # auto-adopt test fixtures (site_without_auto_adopt)
)


async def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--yes",
        action="store_true",
        help="Skip the interactive confirmation prompt",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be deleted, then exit without changes",
    )
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

    from app.db import async_session_factory

    async with async_session_factory() as session:
        # 1. Identify candidates. The query joins to devices.devices via
        # core.sites so we refuse to touch any org that owns real
        # inventory, regardless of its name.
        prefix_clause = " OR ".join(f"o.name LIKE '{p}%'" for p in FIXTURE_PREFIXES)
        candidates = (
            await session.execute(
                text(f"""
            SELECT
              o.id, o.name,
              COUNT(DISTINCT s.id) AS sites,
              COUNT(DISTINCT a.id) AS agents,
              COUNT(DISTINCT d.id) AS devices
            FROM core.organizations o
            LEFT JOIN core.sites s ON s.organization_id = o.id AND s.deleted_at IS NULL
            LEFT JOIN agents.remote_agents a ON a.organization_id = o.id AND a.deleted_at IS NULL
            LEFT JOIN devices.devices d ON d.site_id = s.id AND d.deleted_at IS NULL
            WHERE o.deleted_at IS NULL AND ({prefix_clause})
            GROUP BY o.id, o.name
            HAVING COUNT(DISTINCT d.id) = 0
            ORDER BY o.name
        """)
            )
        ).all()

        if not candidates:
            print("Nothing to purge. The fixture pool is already clean.")
            return 0

        total_sites = sum(row.sites for row in candidates)
        total_agents = sum(row.agents for row in candidates)

        print(f"Found {len(candidates)} fixture organization(s) to soft-delete:")
        print(f"  → {total_sites} site(s), {total_agents} agent(s)")
        print("  → 0 device row(s)  (orgs with real inventory are skipped)")
        print()
        for row in candidates[:10]:
            print(f"  {row.name}  ({row.sites} site, {row.agents} agent)")
        if len(candidates) > 10:
            print(f"  ... and {len(candidates) - 10} more")
        print()

        if args.dry_run:
            print("(dry-run — no changes made)")
            return 0

        if not args.yes:
            answer = input("Proceed? [y/N] ").strip().lower()
            if answer != "y":
                print("Cancelled.")
                return 1

        # 2. Soft-delete. Order matters: dependents first, then the org,
        # so any concurrent reader that filters dependents by org
        # deleted_at sees a consistent snapshot mid-script.
        now = datetime.now(UTC)
        org_ids = [row.id for row in candidates]

        stamped_agents = (
            await session.execute(
                text("""
            UPDATE agents.remote_agents
               SET deleted_at = :now
             WHERE organization_id = ANY(:ids) AND deleted_at IS NULL
            RETURNING id
        """),
                {"now": now, "ids": org_ids},
            )
        ).all()

        stamped_sites = (
            await session.execute(
                text("""
            UPDATE core.sites
               SET deleted_at = :now
             WHERE organization_id = ANY(:ids) AND deleted_at IS NULL
            RETURNING id
        """),
                {"now": now, "ids": org_ids},
            )
        ).all()

        stamped_orgs = (
            await session.execute(
                text("""
            UPDATE core.organizations
               SET deleted_at = :now
             WHERE id = ANY(:ids) AND deleted_at IS NULL
            RETURNING id
        """),
                {"now": now, "ids": org_ids},
            )
        ).all()

        await session.commit()

        print()
        print(
            f"Done. Soft-deleted {len(stamped_orgs)} org(s), "
            f"{len(stamped_sites)} site(s), "
            f"{len(stamped_agents)} agent(s)."
        )
        return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
