# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2024-2026 FreeSDN
"""FreeSDN - Omada adapter package."""

from app.adapters.omada.adapter import OmadaAdapter
from app.adapters.omada.client import OmadaApiClient, OmadaClientConfig
from app.adapters.omada.exceptions import (
    OmadaApiError,
    OmadaAuthError,
    OmadaAuthorizationError,
    OmadaConnectionError,
    OmadaDeviceOfflineError,
    OmadaError,
    OmadaNotFoundError,
    OmadaRateLimitError,
    OmadaSessionExpiredError,
    OmadaTimeoutError,
    OmadaUnsupportedVersionError,
    OmadaValidationError,
)
from app.adapters.omada.models import (
    # --- Enterprise Normalized Models ---
    NormalizedACLRule,
    # --- Omada API Models ---
    NormalizedAPDetail,
    NormalizedChannelUtil,
    NormalizedClient,
    NormalizedDHCPReservation,
    NormalizedEvent,
    NormalizedFirewallRule,
    NormalizedFirmwareOverview,
    NormalizedFirmwareStatus,
    NormalizedGatewayDetail,
    NormalizedGatewayPort,
    NormalizedHotspotConfig,
    NormalizedIPGroup,
    NormalizedIPMACBinding,
    NormalizedMACTableEntry,
    NormalizedPoESchedule,
    NormalizedPort,
    NormalizedPortProfile,
    NormalizedRogueAP,
    NormalizedSiteSettings,
    NormalizedSsid,
    NormalizedStaticRoute,
    NormalizedSwitchDetail,
    NormalizedTopologyDevice,
    NormalizedVlan,
    NormalizedVoucher,
    OmadaAccessPoint,
    OmadaApiEnvelope,
    OmadaAPLanPortSettings,
    OmadaClient,
    OmadaControllerInfo,
    OmadaControllerStatus,
    OmadaDevice,
    OmadaDeviceMetrics,
    OmadaFirewallRule,
    OmadaFirmwareInfo,
    OmadaGateway,
    OmadaGatewayPortConfig,
    # --- Enums ---
    OmadaGatewayPortMode,
    OmadaGatewayPortStatus,
    OmadaGatewayPortType,
    OmadaLinkDuplex,
    OmadaLinkSpeed,
    OmadaNetwork,
    OmadaPaginatedData,
    OmadaPoEMode,
    OmadaPortOperation,
    OmadaPortProfile,
    OmadaPortStatistics,
    OmadaPortType,
    OmadaSite,
    OmadaSsid,
    OmadaSwitchPort,
    OmadaWanConfig,
)

__all__ = [
    # Adapter & Client
    "OmadaAdapter",
    "OmadaApiClient",
    "OmadaClientConfig",
    # Exceptions
    "OmadaError",
    "OmadaApiError",
    "OmadaAuthError",
    "OmadaAuthorizationError",
    "OmadaConnectionError",
    "OmadaDeviceOfflineError",
    "OmadaNotFoundError",
    "OmadaRateLimitError",
    "OmadaSessionExpiredError",
    "OmadaTimeoutError",
    "OmadaUnsupportedVersionError",
    "OmadaValidationError",
    # Enums
    "OmadaGatewayPortType",
    "OmadaGatewayPortMode",
    "OmadaLinkSpeed",
    "OmadaLinkDuplex",
    "OmadaPoEMode",
    "OmadaPortType",
    "OmadaPortOperation",
    # Omada API Models
    "OmadaApiEnvelope",
    "OmadaPaginatedData",
    "OmadaControllerInfo",
    "OmadaControllerStatus",
    "OmadaSite",
    "OmadaDevice",
    "OmadaSwitchPort",
    "OmadaPortStatistics",
    "OmadaNetwork",
    "OmadaSsid",
    "OmadaClient",
    "OmadaAccessPoint",
    "OmadaGateway",
    "OmadaGatewayPortStatus",
    "OmadaGatewayPortConfig",
    "OmadaAPLanPortSettings",
    "OmadaWanConfig",
    "OmadaFirewallRule",
    "OmadaPortProfile",
    "OmadaFirmwareInfo",
    "OmadaDeviceMetrics",
    # Normalized Output Models
    "NormalizedPort",
    "NormalizedGatewayDetail",
    "NormalizedGatewayPort",
    "NormalizedSwitchDetail",
    "NormalizedAPDetail",
    "NormalizedVlan",
    "NormalizedSsid",
    "NormalizedClient",
    "NormalizedFirewallRule",
    "NormalizedPortProfile",
    # Enterprise Normalized Models
    "NormalizedACLRule",
    "NormalizedChannelUtil",
    "NormalizedDHCPReservation",
    "NormalizedEvent",
    "NormalizedFirmwareOverview",
    "NormalizedFirmwareStatus",
    "NormalizedHotspotConfig",
    "NormalizedIPGroup",
    "NormalizedIPMACBinding",
    "NormalizedMACTableEntry",
    "NormalizedPoESchedule",
    "NormalizedRogueAP",
    "NormalizedSiteSettings",
    "NormalizedStaticRoute",
    "NormalizedTopologyDevice",
    "NormalizedVoucher",
]
