/// <reference types="vitest" />
import { defineConfig } from 'vite';
import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import path from 'path';
import { readFileSync, writeFileSync } from 'fs';
import { execSync } from 'child_process';

const pkg = JSON.parse(readFileSync(path.resolve(__dirname, 'package.json'), 'utf-8'));

// Detect Node and npm versions at build time
const nodeVersion = process.versions.node;
let npmVersion = 'unknown';
try {
  npmVersion = execSync('npm --version', { encoding: 'utf-8' }).trim();
} catch { /* fallback */ }

// Generate build-info.ts with frontend package versions from package.json
const buildInfoContent = `// Auto-generated by vite.config.ts (do not edit manually)
export const FRONTEND_VERSIONS: Record<string, string> = ${JSON.stringify({
  node: nodeVersion,
  npm: npmVersion,
  react: pkg.dependencies.react?.replace(/^\^/, '') ?? 'unknown',
  'react-router': pkg.dependencies['react-router-dom']?.replace(/^\^/, '') ?? 'unknown',
  tailwindcss: pkg.devDependencies.tailwindcss?.replace(/^\^/, '') ?? 'unknown',
  typescript: pkg.devDependencies.typescript?.replace(/^\^/, '') ?? 'unknown',
  vite: pkg.devDependencies.vite?.replace(/^\^/, '') ?? 'unknown',
  zustand: pkg.dependencies.zustand?.replace(/^\^/, '') ?? 'unknown',
}, null, 2)};
`;
writeFileSync(path.resolve(__dirname, 'src/lib/build-info.ts'), buildInfoContent);

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    tailwindcss(),
    react(),
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  server: {
    port: 5173,
    host: true,
    watch: {
      usePolling: true,
      interval: 1000,
    },
    proxy: {
      '/api': {
        // VITE_PROXY_TARGET is for server-side proxy (inside Docker: http://api:8000)
        // Falls back to VITE_API_URL or localhost for local dev
        target: process.env.VITE_PROXY_TARGET || process.env.VITE_API_URL || 'http://localhost:8000',
        changeOrigin: true,
        // ws: true is REQUIRED for the realtime feed at /api/v1/ws.
        // Without it, every WebSocket connect times out with code 1006
        // every ~4s, the FE shows a persistent "Disconnected" banner
        // and event-bus updates never reach any page.
        ws: true,
        // Defensive: if a backend route still emits a Location header
        // pointing at the internal hostname (``http://api:8000/...``),
        // rewrite it back to the proxy origin so the browser can follow.
        // Belt-and-suspenders alongside the FastAPI path-normalize
        // middleware that prevents the redirect from ever being emitted
        // in the first place.
        autoRewrite: true,
        // protocolRewrite: keep http for dev, prevent accidental
        // ``https://api:8000`` leak if some future route 30x's there.
        protocolRewrite: 'http',
      },
    },
  },
  test: {
    globals: true,
    environment: 'happy-dom',
    setupFiles: ['./src/test/setup.ts'],
    css: false,
    include: ['src/**/*.{test,spec}.{ts,tsx}'],
    coverage: {
      reporter: ['text', 'html'],
      include: ['src/components/ui/**', 'src/components/layout/**', 'src/components/ErrorBoundary.tsx'],
    },
  },
  build: {
    outDir: 'dist',
    sourcemap: process.env.NODE_ENV === 'production' ? false : true,
    chunkSizeWarningLimit: 1500,
    rollupOptions: {
      output: {
        manualChunks(id) {
          if (!id.includes('node_modules')) return;

          // vendor-tanstack: data & virtualisation (isolated, no circular deps)
          if (id.includes('@tanstack/')) {
            return 'vendor-tanstack';
          }

          // vendor: all other node_modules in one chunk
          // (React ecosystem has inherent circular imports between react,
          // radix-ui, recharts, d3, etc., splitting causes warnings)
          return 'vendor';
        },
      },
    },
  },
});
