# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2024-2026 FreeSDN
"""
Tests for ``BackupEncryption`` versioned ``key_id`` (readiness).

Historical backups used PBKDF2-SHA256 at 100,000 iterations and stored the
salt directly as a base64-urlsafe string in the ``backup.encryption_key_id``
column. OWASP 2025 raised the minimum to 600,000 — the
backup/restore chapter introduced a versioned ``key_id`` format so the
upgrade is backwards-compatible:

  v1 (legacy, decrypt-only):  ``<base64-urlsafe-salt>``
                               iterations implicit = 100,000
  v2 (current, default):      ``v2:<iterations>:<base64-urlsafe-salt>``

These tests assert both formats round-trip correctly, that v1 decrypt still
works on archives written by the historical code path, and that a future
iteration bump (e.g. 800k or 1.2M) is already supported by parsing the
iteration count out of the v2 key_id at decrypt time.
"""

from __future__ import annotations

import base64
import os

import pytest

from app.services.backup import BackupEncryption


@pytest.fixture
def enc() -> BackupEncryption:
    """A BackupEncryption with a deterministic master key — keeps tests fast.

    We bypass ``settings.SECRET_KEY`` so tests don't depend on the
    autogenerated ephemeral key from pydantic. The master key value is
    irrelevant — only the round-trip property matters.
    """
    return BackupEncryption(master_key="test-master-key-with-enough-entropy-2026")


# ── current (v2) format ─────────────────────────────────────────────────


def test_v2_round_trip(enc: BackupEncryption) -> None:
    data = b"sample backup payload \xff\x00\xa1 bytes"
    ct, kid = enc.encrypt(data)
    assert kid.startswith("v2:")
    # The iteration count embedded in the key_id must match the current
    # PBKDF2_ITERATIONS class constant — otherwise a future bump would
    # silently break this assertion.
    assert kid.startswith(f"v2:{BackupEncryption.PBKDF2_ITERATIONS}:")
    assert enc.decrypt(ct, kid) == data


def test_v2_key_id_carries_iteration_count(enc: BackupEncryption) -> None:
    _, kid = enc.encrypt(b"x")
    iterations, salt_b64 = BackupEncryption._parse_key_id(kid)
    assert iterations == BackupEncryption.PBKDF2_ITERATIONS
    # Salt must be valid base64-urlsafe of exactly 16 random bytes.
    assert len(base64.urlsafe_b64decode(salt_b64.encode())) == 16


def test_v2_each_encrypt_uses_fresh_salt(enc: BackupEncryption) -> None:
    """A backup of the same plaintext must NEVER produce identical
    ciphertext + key_id — otherwise an attacker who recognises one
    backup blob's content can confirm the same plaintext in another."""
    ct1, kid1 = enc.encrypt(b"identical plaintext")
    ct2, kid2 = enc.encrypt(b"identical plaintext")
    assert kid1 != kid2  # different salts
    assert ct1 != ct2    # different ciphertexts


def test_v2_forward_iteration_bump_decrypts(enc: BackupEncryption) -> None:
    """A v2 key_id can carry an iteration count OTHER than the current
    default — a future bump (or a legacy archive that explicitly wrote
    a non-default count) must still decrypt cleanly."""
    from cryptography.fernet import Fernet
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC

    salt = os.urandom(16)
    future_iter = 1_200_000  # 2× the current 600k
    kdf = PBKDF2HMAC(
        algorithm=hashes.SHA256(), length=32, salt=salt, iterations=future_iter,
    )
    key = base64.urlsafe_b64encode(kdf.derive(enc.master_key.encode()))
    ct = Fernet(key).encrypt(b"forward-compat payload")
    kid = f"v2:{future_iter}:{base64.urlsafe_b64encode(salt).decode()}"
    assert enc.decrypt(ct, kid) == b"forward-compat payload"


# ── legacy (v1) format ──────────────────────────────────────────────────


def test_v1_legacy_decrypt(enc: BackupEncryption) -> None:
    """A backup written by the historical code (bare base64 salt as
    ``key_id``, implicit 100k iterations) must still decrypt after the
    upgrade. Otherwise every existing archive is lost."""
    from cryptography.fernet import Fernet
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC

    salt = os.urandom(16)
    kdf = PBKDF2HMAC(
        algorithm=hashes.SHA256(), length=32, salt=salt, iterations=100_000,
    )
    legacy_key = base64.urlsafe_b64encode(kdf.derive(enc.master_key.encode()))
    legacy_ct = Fernet(legacy_key).encrypt(b"backup from the old code path")

    # The historical code stored the bare salt as key_id.
    legacy_kid = base64.urlsafe_b64encode(salt).decode()

    assert enc.decrypt(legacy_ct, legacy_kid) == b"backup from the old code path"


def test_v1_parse_returns_legacy_iteration_count() -> None:
    """``_parse_key_id`` on a bare-base64 salt must return 100k."""
    bare = base64.urlsafe_b64encode(os.urandom(16)).decode()
    iterations, salt_b64 = BackupEncryption._parse_key_id(bare)
    assert iterations == 100_000
    assert salt_b64 == bare


# ── malformed input ─────────────────────────────────────────────────────


def test_v2_key_id_with_non_numeric_iterations_raises(enc: BackupEncryption) -> None:
    """A garbled v2 key_id must raise a clear ValueError — not silently
    derive a wrong key and surface a Fernet ``InvalidToken`` later."""
    ct, _ = enc.encrypt(b"x")
    with pytest.raises(ValueError, match="non-numeric"):
        enc.decrypt(ct, "v2:notanumber:somesaltbase64")


def test_v2_key_id_missing_segments_raises(enc: BackupEncryption) -> None:
    """``v2`` prefix without the three required colon-separated parts."""
    ct, _ = enc.encrypt(b"x")
    with pytest.raises(ValueError, match="malformed v2"):
        enc.decrypt(ct, "v2:600000")  # missing salt


def test_decrypt_with_wrong_key_id_raises(enc: BackupEncryption) -> None:
    """Even a well-formed v2 key_id derives a different key if the salt
    doesn't match — Fernet must reject the resulting MAC mismatch."""
    from cryptography.fernet import InvalidToken

    ct, _ = enc.encrypt(b"original")
    wrong_kid = f"v2:600000:{base64.urlsafe_b64encode(os.urandom(16)).decode()}"
    with pytest.raises(InvalidToken):
        enc.decrypt(ct, wrong_kid)


# ── upgrade path: old key_id, new code, then re-encrypt ────────────────


def test_decrypt_v1_then_re_encrypt_writes_v2(enc: BackupEncryption) -> None:
    """The realistic upgrade flow: a backup written by old code is
    decrypted (v1 path), then re-encrypted (v2 path). Operators / a
    future migration script can use this round-trip to upgrade
    existing archives to the stronger KDF."""
    from cryptography.fernet import Fernet
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC

    salt = os.urandom(16)
    kdf = PBKDF2HMAC(
        algorithm=hashes.SHA256(), length=32, salt=salt, iterations=100_000,
    )
    v1_key = base64.urlsafe_b64encode(kdf.derive(enc.master_key.encode()))
    v1_ct = Fernet(v1_key).encrypt(b"legacy archive")
    v1_kid = base64.urlsafe_b64encode(salt).decode()

    plaintext = enc.decrypt(v1_ct, v1_kid)
    v2_ct, v2_kid = enc.encrypt(plaintext)

    assert v2_kid.startswith(f"v2:{BackupEncryption.PBKDF2_ITERATIONS}:")
    assert enc.decrypt(v2_ct, v2_kid) == b"legacy archive"
