// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2024-2026 FreeSDN
/**
 * CameraReportsPage, lists the daily camera-summary reports generated by the
 * cameras.generate_daily_report beat task (camera counts, 24h event totals,
 * uptime %). Read-only: the backend produces one daily_summary row per org per
 * day; this surfaces them so operators don't have to query the API by hand.
 */
import { useTranslation } from 'react-i18next';
import { useQuery } from '@tanstack/react-query';
import { Activity, CalendarDays, Camera, FileBarChart, Loader2 } from 'lucide-react';

import { cameraReportsApi, type CameraReport } from '@/lib/api';
import { PageHeader } from '@/components/layout';
import { Card, CardContent } from '@/components/ui/card';
import { EmptyState, ErrorState } from '@/components/ui/empty-state';

function pct(v?: number): string {
  if (v === undefined || v === null) return '-';
  return `${v.toFixed(1)}%`;
}

function uptimeColor(v?: number): string {
  if (v === undefined || v === null) return 'text-muted-foreground';
  if (v >= 99) return 'text-green-600';
  if (v >= 95) return 'text-amber-600';
  return 'text-destructive';
}

export default function CameraReportsPage() {
  const { t } = useTranslation('cameras');

  const { data, isLoading, isError, refetch } = useQuery({
    queryKey: ['camera-reports'],
    queryFn: () => cameraReportsApi.list({ limit: 60 }).then((r) => r.data.items),
  });

  return (
    <div className="space-y-4 p-4">
      <PageHeader
        title={t('CameraReportsPage.title')}
        description={t('CameraReportsPage.description')}
        icon={FileBarChart}
      />

      {isLoading ? (
        <div className="flex items-center justify-center py-16 text-muted-foreground">
          <Loader2 className="h-5 w-5 animate-spin" />
        </div>
      ) : isError ? (
        <ErrorState
          message={t('CameraReportsPage.error.description')}
          onRetry={() => refetch()}
        />
      ) : !data || data.length === 0 ? (
        <EmptyState
          icon={FileBarChart}
          title={t('CameraReportsPage.empty.title')}
          description={t('CameraReportsPage.empty.description')}
        />
      ) : (
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          {data.map((rep: CameraReport) => (
            <Card key={rep.id}>
              <CardContent className="space-y-3 p-4">
                <div className="flex items-center justify-between">
                  <span className="inline-flex items-center gap-1.5 text-sm font-medium">
                    <CalendarDays className="h-4 w-4 text-muted-foreground" />
                    {new Date(rep.period_start).toLocaleDateString()}
                  </span>
                  <span className="text-[11px] uppercase tracking-wide text-muted-foreground">
                    {t('CameraReportsPage.dailySummary')}
                  </span>
                </div>

                <div className="flex items-baseline gap-2">
                  <span className={`text-2xl font-semibold ${uptimeColor(rep.data.uptime_pct)}`}>
                    {pct(rep.data.uptime_pct)}
                  </span>
                  <span className="text-xs text-muted-foreground">
                    {t('CameraReportsPage.uptime')}
                  </span>
                </div>

                <div className="grid grid-cols-3 gap-2 text-center">
                  <div>
                    <div className="inline-flex items-center gap-1 text-sm font-medium">
                      <Camera className="h-3.5 w-3.5 text-muted-foreground" />
                      {rep.data.online_cameras ?? 0}/{rep.data.total_cameras ?? 0}
                    </div>
                    <div className="text-[11px] text-muted-foreground">
                      {t('CameraReportsPage.online')}
                    </div>
                  </div>
                  <div>
                    <div className="inline-flex items-center gap-1 text-sm font-medium">
                      <Activity className="h-3.5 w-3.5 text-muted-foreground" />
                      {rep.data.total_events ?? 0}
                    </div>
                    <div className="text-[11px] text-muted-foreground">
                      {t('CameraReportsPage.events24h')}
                    </div>
                  </div>
                  <div>
                    <div className="text-sm font-medium">{rep.data.total_snapshots ?? 0}</div>
                    <div className="text-[11px] text-muted-foreground">
                      {t('CameraReportsPage.samples')}
                    </div>
                  </div>
                </div>

                <div className="text-[11px] text-muted-foreground">
                  {t('CameraReportsPage.generated')}{' '}
                  {new Date(rep.generated_at).toLocaleString()}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
