# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2024-2026 FreeSDN
"""
FreeSDN - Schemas Package
=============================

Pydantic schemas for request/response validation.
"""

from app.schemas.agents import (
    AgentAuthRequest,
    AgentAuthResponse,
    AgentCommandMessage,
    AgentRegisterRequest,
    AgentRegisterResponse,
    AgentResponse,
    AgentStatsResponse,
    AgentSummary,
    AgentUpdateRequest,
    AgentWebSocketAuth,
    HeartbeatCreate,
    HeartbeatResponse,
    TaskCreate,
    TaskResponse,
    TaskUpdate,
)
from app.schemas.alert_rules import (
    AlertAcknowledge,
    AlertListResponse,
    AlertResolve,
    AlertResponse,
    AlertRuleCreate,
    AlertRuleEvaluateRequest,
    AlertRuleListResponse,
    AlertRuleResponse,
    AlertRuleStatsResponse,
    AlertRuleUpdate,
    AlertSuppress,
)
from app.schemas.analytics import (
    AlertCreateRequest,
    AlertUpdateRequest,
    ClientAnalyticsResponse,
    DashboardSummaryResponse,
    DeviceHealthResponse,
    MetricDataPointResponse,
    MetricDefinitionCreate,
    MetricDefinitionResponse,
    MetricDefinitionUpdate,
    MetricQueryRequest,
    MetricQueryResponse,
    MetricRecordRequest,
    NetworkOverviewResponse,
    TrafficAnalyticsResponse,
    WidgetCreateRequest,
    WidgetResponse,
    WidgetUpdateRequest,
)
from app.schemas.backup import (
    BackupCreate,
    BackupListResponse,
    BackupResponse,
    BackupScheduleCreate,
    BackupScheduleResponse,
    BackupScheduleUpdate,
    BackupStats,
    ImportResult,
    RestoreJobResponse,
    RestoreRequest,
    StorageLocationCreate,
    StorageLocationResponse,
    StorageLocationTestResult,
    StorageLocationUpdate,
    StorageTypeInfo,
    SupportedStorageTypes,
)
from app.schemas.core import (
    BrowserAuthResponse,
    ControllerCreate,
    ControllerProbe,
    ControllerResponse,
    ControllerUpdate,
    ControllerWithStats,
    LoginRequest,
    MessageResponse,
    MfaDisableRequest,
    MfaEnableRequest,
    MfaLoginRequest,
    MfaSetupRequest,
    MfaSetupResponse,
    OrganizationCreate,
    OrganizationDashboard,  # noqa: F401
    OrganizationResponse,
    OrganizationUpdate,
    OrganizationWithStats,
    PaginatedResponse,
    PaginationParams,
    PasswordChangeRequest,
    PasswordResetConfirmSchema,
    PasswordResetRequestSchema,
    ProfileUpdateRequest,
    RefreshTokenRequest,
    RegisterRequest,
    SiteCreate,
    SiteResponse,
    SiteSubnet,
    SiteUpdate,
    SiteWithStats,
    TokenPayload,
    TokenResponse,
    UserCreate,
    UserResponse,
    UserSiteAccessBulk,  # noqa: F401
    UserSiteAccessCreate,  # noqa: F401
    UserSiteAccessResponse,  # noqa: F401
    UserUpdate,
    UserWithOrg,
)
from app.schemas.correlation import (
    CorrelationRuleCreate,
    CorrelationRuleListResponse,
    CorrelationRuleResponse,
    CorrelationRuleUpdate,
    CorrelationStatsResponse,
    CorrelationTriggerRequest,
    IncidentCreate,
    IncidentEventResponse,
    IncidentListResponse,
    IncidentResponse,
    IncidentUpdate,
)
from app.schemas.credentials import (
    CredentialCreate,
    CredentialResponse,
    CredentialTestRequest,
    CredentialTestResponse,
    CredentialUpdate,
)
from app.schemas.devices import (
    DeviceClientBase,
    DeviceClientResponse,
    DeviceCreate,
    DevicePortBase,
    DevicePortResponse,
    DeviceResponse,
    DeviceStats,
    DeviceSummary,
    DeviceUpdate,
    DeviceWithStats,
    SiteDeviceStats,
)
from app.schemas.discovery import (
    ControllerDiscoveryRequest,
    ControllerDiscoveryResponse,
    DiscoveredHostSchema,
    DriverDetailsSchema,
    DriverSchema,
    FingerprintRequestSchema,
    FingerprintResultSchema,
    ScanOptionsSchema,
    ScanProgressSchema,
    ScanRequestSchema,
    ScanResultsSchema,
    ScanStartedResponse,
)
from app.schemas.enterprise import (
    ConfigTemplateCreate,
    ConfigTemplateResponse,
    ConfigTemplateUpdate,
    DeviceConfigOverridesUpdate,
    DeviceConfigSettingsUpdate,
    DeviceGroupCreate,
    DeviceGroupResponse,
    DeviceGroupUpdate,
    DeviceLifecycleResponse,
    DeviceTagsResponse,
    DeviceTagsUpdate,
    LifecycleLogEntry,
    LifecycleTransitionRequest,
    OrgHealthSummary,
    ResolvedConfigResponse,
    SiteGroupCreate,
    SiteGroupResponse,
    SiteGroupUpdate,
    SiteHealthSummary,
)
from app.schemas.enterprise import (
    DeviceConfigResponse as EnterpriseDeviceConfigResponse,
)
from app.schemas.enterprise import (
    DeviceHealthResponse as EnterpriseHealthResponse,
)
from app.schemas.firmware import (
    CheckUpdatesRequest,
    CompatibilityCheckRequest,
    CompatibilityCheckResponse,
    DeviceFirmwareStatusListResponse,
    DeviceFirmwareStatusResponse,
    DeviceRollbackRequest,
    FirmwareCreate,
    FirmwareListResponse,
    FirmwareResponse,
    FirmwareSummaryResponse,
    FirmwareUpdate,
    ScheduleCreate,
    ScheduleListResponse,
    ScheduleResponse,
    ScheduleUpdate,
    UpgradeJobCreate,
    UpgradeJobListResponse,
    UpgradeJobResponse,
)
from app.schemas.import_export import (
    DataJobSummary,
    ExportJobListResponse,
    ExportJobResponse,
    ExportRequest,
    ImportJobListResponse,
    ImportJobResponse,
    ImportPreviewRequest,
    ImportRequest,
    ImportValidationResult,
)
from app.schemas.security_audit import (
    AnomalyResolve,
    AuditLogListResponse,
    AuditLogQuery,
    AuditLogResponse,
    ComplianceReportResponse,
    FailedLoginListResponse,
    FailedLoginResponse,
    IPActivityResponse,
    IPBlockCreate,
    IPBlockListResponse,
    IPBlockResponse,
    SecurityAnomalyListResponse,
    SecurityAnomalyResponse,
    SecurityEventListResponse,
    SecurityEventQuery,
    SecurityEventResponse,
    SecurityEventReview,
    SecurityExportRequest,
    SecurityExportResponse,
    SecuritySummaryResponse,
    UserActivityResponse,
)
from app.schemas.sla import (
    SLABreachAcknowledge,
    SLABreachListResponse,
    SLABreachResponse,
    SLAComplianceSummary,
    SLAPolicyCreate,
    SLAPolicyListResponse,
    SLAPolicyResponse,
    SLAPolicyUpdate,
    SLASnapshotResponse,
)
from app.schemas.sso import (
    LDAPAuthRequest,
    SSOAuthorizeRequest,
    SSOAuthorizeResponse,
    SSOCallbackRequest,
    SSOCallbackResponse,
    SSOProviderCreate,
    SSOProviderPublic,
    SSOProviderResponse,
    SSOProviderUpdate,
    SSOTestConnectionRequest,
    SSOTestConnectionResponse,
    SSOUserInfo,
)
from app.schemas.topology import (
    TopologyEdge,
    TopologyGraphResponse,
    TopologyLayoutResponse,
    TopologyLayoutSave,
    TopologyNode,
    TopologyStats,
)
from app.schemas.vpn import (
    ConnectivityCheckRequest,
    ConnectivityCheckResponse,
    SiteVPNConfigCreate,
    SiteVPNConfigResponse,
    SiteVPNConfigUpdate,
    TailscaleNodeResponse,
    TailscaleStatusResponse,
    VPNConnectionResponse,
    VPNHealthCheckResponse,
    VPNStatusSummaryResponse,
    VPNSubnetResponse,
)
from app.schemas.webhooks import (
    WebhookCreate,
    WebhookDeliveryListResponse,
    WebhookDeliveryResponse,
    WebhookListResponse,
    WebhookResponse,
    WebhookStatsResponse,
    WebhookTestResponse,
    WebhookUpdate,
)

__all__ = [
    # Common
    "MessageResponse",
    # Auth
    "BrowserAuthResponse",
    "TokenResponse",
    "TokenPayload",
    "LoginRequest",
    "RefreshTokenRequest",
    "PasswordChangeRequest",
    # User
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserWithOrg",
    # Organization
    "OrganizationCreate",
    "OrganizationUpdate",
    "OrganizationResponse",
    "OrganizationWithStats",
    # Site
    "SiteCreate",
    "SiteSubnet",
    "SiteUpdate",
    "SiteResponse",
    "SiteWithStats",
    # Controller
    "ControllerCreate",
    "ControllerProbe",
    "ControllerUpdate",
    "ControllerResponse",
    "ControllerWithStats",
    # Device
    "DeviceCreate",
    "DeviceUpdate",
    "DeviceResponse",
    "DeviceWithStats",
    "DeviceSummary",
    "DeviceStats",
    "SiteDeviceStats",
    # Device Port
    "DevicePortBase",
    "DevicePortResponse",
    # Device Client
    "DeviceClientBase",
    "DeviceClientResponse",
    # Pagination
    "PaginationParams",
    "PaginatedResponse",
    # Agents
    "AgentRegisterRequest",
    "AgentRegisterResponse",
    "AgentResponse",
    "AgentSummary",
    "AgentUpdateRequest",
    "AgentStatsResponse",
    "HeartbeatCreate",
    "HeartbeatResponse",
    "TaskCreate",
    "TaskUpdate",
    "TaskResponse",
    "AgentAuthRequest",
    "AgentAuthResponse",
    "AgentWebSocketAuth",
    "AgentCommandMessage",
    # Analytics
    "MetricDefinitionCreate",
    "MetricDefinitionUpdate",
    "MetricDefinitionResponse",
    "MetricQueryRequest",
    "MetricQueryResponse",
    "MetricRecordRequest",
    "MetricDataPointResponse",
    "DashboardSummaryResponse",
    "DeviceHealthResponse",
    "TrafficAnalyticsResponse",
    "ClientAnalyticsResponse",
    "NetworkOverviewResponse",
    "AlertCreateRequest",
    "AlertUpdateRequest",
    "AlertResponse",
    "WidgetCreateRequest",
    "WidgetUpdateRequest",
    "WidgetResponse",
    # VPN
    "VPNConnectionResponse",
    "TailscaleNodeResponse",
    "TailscaleStatusResponse",
    "VPNSubnetResponse",
    "SiteVPNConfigCreate",
    "SiteVPNConfigUpdate",
    "SiteVPNConfigResponse",
    "ConnectivityCheckRequest",
    "ConnectivityCheckResponse",
    "VPNHealthCheckResponse",
    "VPNStatusSummaryResponse",
    # Security Audit
    "AuditLogResponse",
    "AuditLogListResponse",
    "AuditLogQuery",
    "SecurityEventResponse",
    "SecurityEventListResponse",
    "SecurityEventQuery",
    "SecurityEventReview",
    "SecuritySummaryResponse",
    "IPBlockResponse",
    "IPBlockCreate",
    "IPBlockListResponse",
    "IPActivityResponse",
    "FailedLoginResponse",
    "FailedLoginListResponse",
    "SecurityAnomalyResponse",
    "SecurityAnomalyListResponse",
    "AnomalyResolve",
    "UserActivityResponse",
    "ComplianceReportResponse",
    "SecurityExportRequest",
    "SecurityExportResponse",
    # Data Import/Export
    "ExportRequest",
    "ExportJobResponse",
    "ExportJobListResponse",
    "ImportValidationResult",
    "ImportPreviewRequest",
    "ImportRequest",
    "ImportJobResponse",
    "ImportJobListResponse",
    "DataJobSummary",
    # Firmware
    "FirmwareCreate",
    "FirmwareUpdate",
    "FirmwareResponse",
    "FirmwareListResponse",
    "FirmwareSummaryResponse",
    "DeviceFirmwareStatusResponse",
    "DeviceFirmwareStatusListResponse",
    "UpgradeJobCreate",
    "UpgradeJobResponse",
    "UpgradeJobListResponse",
    "ScheduleCreate",
    "ScheduleUpdate",
    "ScheduleResponse",
    "ScheduleListResponse",
    "CompatibilityCheckRequest",
    "CompatibilityCheckResponse",
    "DeviceRollbackRequest",
    "CheckUpdatesRequest",
    # Webhooks
    "WebhookCreate",
    "WebhookUpdate",
    "WebhookResponse",
    "WebhookListResponse",
    "WebhookDeliveryResponse",
    "WebhookDeliveryListResponse",
    "WebhookStatsResponse",
    "WebhookTestResponse",
    # Enterprise Config Management
    "SiteGroupCreate",
    "SiteGroupUpdate",
    "SiteGroupResponse",
    "DeviceGroupCreate",
    "DeviceGroupUpdate",
    "DeviceGroupResponse",
    "DeviceTagsUpdate",
    "DeviceTagsResponse",
    "ConfigTemplateCreate",
    "ConfigTemplateUpdate",
    "ConfigTemplateResponse",
    "EnterpriseDeviceConfigResponse",
    "DeviceConfigOverridesUpdate",
    "DeviceConfigSettingsUpdate",
    "ResolvedConfigResponse",
    "LifecycleTransitionRequest",
    "LifecycleLogEntry",
    "DeviceLifecycleResponse",
    "EnterpriseHealthResponse",
    "SiteHealthSummary",
    "OrgHealthSummary",
    # Backup
    "BackupCreate",
    "BackupResponse",
    "BackupListResponse",
    "BackupStats",
    "BackupScheduleCreate",
    "BackupScheduleUpdate",
    "BackupScheduleResponse",
    "RestoreRequest",
    "RestoreJobResponse",
    "ImportResult",
    "StorageLocationCreate",
    "StorageLocationUpdate",
    "StorageLocationResponse",
    "StorageLocationTestResult",
    "StorageTypeInfo",
    "SupportedStorageTypes",
    # SSO
    "SSOProviderCreate",
    "SSOProviderUpdate",
    "SSOProviderResponse",
    "SSOProviderPublic",
    "SSOAuthorizeRequest",
    "SSOAuthorizeResponse",
    "SSOCallbackRequest",
    "SSOCallbackResponse",
    "SSOUserInfo",
    "LDAPAuthRequest",
    "SSOTestConnectionRequest",
    "SSOTestConnectionResponse",
    # Correlation
    "CorrelationRuleCreate",
    "CorrelationRuleUpdate",
    "CorrelationRuleResponse",
    "CorrelationRuleListResponse",
    "CorrelationStatsResponse",
    "CorrelationTriggerRequest",
    "IncidentCreate",
    "IncidentUpdate",
    "IncidentResponse",
    "IncidentListResponse",
    "IncidentEventResponse",
    # SLA
    "SLAPolicyCreate",
    "SLAPolicyUpdate",
    "SLAPolicyResponse",
    "SLAPolicyListResponse",
    "SLABreachResponse",
    "SLABreachListResponse",
    "SLABreachAcknowledge",
    "SLASnapshotResponse",
    "SLAComplianceSummary",
    # Topology
    "TopologyNode",
    "TopologyEdge",
    "TopologyGraphResponse",
    "TopologyStats",
    "TopologyLayoutSave",
    "TopologyLayoutResponse",
    # Discovery
    "ScanOptionsSchema",
    "ScanRequestSchema",
    "ScanStartedResponse",
    "ScanProgressSchema",
    "DiscoveredHostSchema",
    "ScanResultsSchema",
    "FingerprintRequestSchema",
    "FingerprintResultSchema",
    "DriverSchema",
    "DriverDetailsSchema",
    "ControllerDiscoveryRequest",
    "ControllerDiscoveryResponse",
    # Credentials
    "CredentialCreate",
    "CredentialUpdate",
    "CredentialResponse",
    "CredentialTestRequest",
    "CredentialTestResponse",
    # Auth (MFA + Password Reset + Registration)
    "RegisterRequest",
    "MfaEnableRequest",
    "MfaSetupRequest",
    "MfaDisableRequest",
    "MfaLoginRequest",
    "MfaSetupResponse",
    "PasswordResetRequestSchema",
    "PasswordResetConfirmSchema",
    "ProfileUpdateRequest",
    # Alert Rules
    "AlertRuleCreate",
    "AlertRuleUpdate",
    "AlertRuleResponse",
    "AlertRuleListResponse",
    "AlertRuleStatsResponse",
    "AlertRuleEvaluateRequest",
    "AlertResponse",
    "AlertListResponse",
    "AlertAcknowledge",
    "AlertResolve",
    "AlertSuppress",
]
